### ISSUE TITLE
module 'stardog' has no attribute 'Admin'

### ISSUE THREAD

**Issue by scardena** [stardog-union/pystardog#134]
as part of the 0.13.0 release, we noticed a breaking change: `module 'stardog' has no attribute 'Admin'`
when importing stardog like this:

```
import stardog
with stardog.Admin(endpoint, auth) as admin:
    # do stuff
```
this was introduced in https://github.com/stardog-union/pystardog/pull/129/files
